### PR TITLE
create test and pylint CI workflows; use devops_tests as a submodule; add show_anim(); bump checkout & setup-python actions in pylint CI job; move more setup entries into pyproject.toml; add example notebook with animation

### PR DESCRIPTION
**Pull request by Sfonxu**
Pull request containing function as mentioned in #29

### CODE REVIEW

**Comment by slayoo** [comment]
@Sfonxu, thanks!

It would be great to:
- [ ] add a brief description of the new routine to the README and
- [ ] add a CI workflow that executes the test notebook (we can use the `test_run_notebooks.py` from the `devops_tests` repo)

BTW, please avoid making pull requests from your fork's `main` branch as it gives other write permission to your `main` branch, and prevents having multiple PRs from one repo (unable to branch out of clean `main`).

**Comment by slayoo** [comment]
Also:
- [ ] the demo notebook was committed with output cleaned up, thus not rendering the anumation

**Comment by Sfonxu** [comment]
> @Sfonxu, thanks!
> 
> It would be great to:
> 
>     * [ ]  add a brief description of the new routine to the README and
> 
>     * [ ]  add a CI workflow that executes the test notebook (we can use the `test_run_notebooks.py` from the `devops_tests` repo)
> 
> 
> BTW, please avoid making pull requests from your fork's `main` branch as:
> 
>     * it gives other write permission to your `main` branch,
> 
>     * it prevents having multiple PRs from one repo (unable to branch out of clean `main`).
> 
>     * will make your `main` branch in conflict with the upstream `main` after merging the PR (since we do squash-merges, i.e. you branch will be rendered at the same time behind and ahead of `upstream:main`)

Thank you for the feedback! I didn't even realize I made the request from main branch. I have added a small description to README.md as well as fixed the notebook and made a test workflow for the whole thing. I'll be more careful next time and make sure I'm actually on a branch.

**Comment by slayoo** [comment]
KUDOS @Sfonxu !

**Review by slayoo — APPROVED** [review]

**Pull request merged**
